### PR TITLE
[codesign] sign macOS arm64 artifacts for 3.7 releases

### PR DESCRIPTION
**Pull request by XilaiZhang**
temporary fix to https://github.com/flutter/flutter/issues/111764

edit existing release codesign script to also codesign darwin-arm64

### CODE REVIEW

**Comment by XilaiZhang** [comment]
cc @jmagman (for some reasons can't add as reviewer)

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by XilaiZhang** [comment]
> LGTM

i am having trouble finding the royalty emoji

**Comment by jmagman** [comment]
LGTM!

**Pull request merged**
