### PR TITLE
update file paths in ios artifacts

### PR DESCRIPTION
**Pull request by XilaiZhang**
I verified that we omitted these files previously. Thanks Christopher and Jenn for pointing this out!

### CODE REVIEW

**Comment by XilaiZhang** [comment]
Would be great if @christopherfujino can review this PR and use it for beta release this week

**Review by jmagman — APPROVED** [review]
See https://github.com/flutter/flutter/pull/102012 where the conductor codesign script was updated.  I'm not sure what this `codesign.py` repo is still used for, does this need to stay in sync with that file?

**Comment by XilaiZhang** [comment]
> See [flutter/flutter#102012](https://github.com/flutter/flutter/pull/102012) where the conductor codesign script was updated. I'm not sure what this `codesign.py` repo is still used for, does this need to stay in sync with that file?

Yeah it is quite unintuitive. we are currently using codesign.py to sign the release artifacts.

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by XilaiZhang** [comment]
Will merge in this now to work with https://github.com/flutter/flutter/issues/111764 together

**Pull request merged**
